### ISSUE TITLE
Add additional text to "Stake Amount (BN string)" field description on PRB Add Worker screen

### ISSUE THREAD

**Issue by yayoi-k** [Phala-Network/runtime-bridge#82]
The "Stake Amount (BN string)" field is ambiguous.  Please add additional text that gives indicates the purpose of the stake.  Is it:
- 'amount of free delegation to assign'
- 'gas amount'
![2022-02-23 20 59 28](https://user-images.githubusercontent.com/2354113/155461254-188e9cab-5c33-4e62-b611-aabc4d4e5785.jpg)

- something else...

"Stake Amount" is the equivalent of saying "Amount" or "Enter a number" it doesn't really mean anything.  Stake amount _"for what"_ or what _"purpose"_?

I'd also suggest indicating what the "Enabled" checkbox means or what that is doing, is that enabling mining or?  Think of it this way, enable _what_.  A checkbox that says "enable" is like saying a checkbox that says "Yes" with a checkmark.  Yes to _what_, or enable _what_

Once I concretely figure it out I'd be happy to write concise words that would fit in the field text to improve the experience for others and increase adoption.

**Comment by jasl** [comment]
@krhougs can you help?

**Comment by krhougs** [comment]
`Stake Amount` equals to the value in the mining page of Phala App.

The value of `enabled` indicates whether the worker should be enabled for mining.

We highly recommend miners to first read about Phala’s [tokenomics](https://wiki.phala.network/en-us/learn/tokenomics/tokenomics/) and [staking mechanism](https://wiki.phala.network/en-us/learn/tokenomics/mining-staking/) to understand the calculation of incomings and how the mining proceeds.

**Comment by yayoi-k** [comment]
Thank you.  How does one obtain the sMax value when using PRB?  The 'start' dialogue box on the mining page of the Phala App shows the sMax but I see no way to obtain this value when adding a worker via PRB.

**Comment by krhougs** [comment]
> Thank you. @krhougs How does one obtain the sMax value when using PRB? The 'start' dialogue box on the mining page of the Phala App shows the sMax but I see no way to obtain this value when adding a worker via PRB.

@yayoi-k You can calculate the value referring https://wiki.phala.network/en-us/learn/tokenomics/tokenomics/#initial-v 
We don't have any plan in adding more features on prb-monitor since it's just an example of calling the prb API.

**Comment by infrachris** [comment]
@krhougs Could you indicate how you personally determine sMax on the miners you've setup, perhaps that would help here.  

Here are the issues I see with determining sMax using the instructions in the tokenomic.
The tokenomic starts with _"A Miner will run a Performance Test and stake some tokens to get the initial V"_
Issue 1: "sudo phala score-test" is no longer a functioning command, it simply repeats the help output:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/2354113/156620927-569aca39-6f04-4acf-ac64-31a9462e3af2.png">
Issue 2: _"...and stake some tokens to get the initial V"_. The way this is written it sounds like one must add the worker and start it with a small stake to determine the initial V, then one can actually decide what stake to put, however one will then have to do a 7 day cool down to stop the miner from the initial small stake to then place the final stake, is this intended?  This seems incredibly and unnecessarily time consuming.  Whereas none of that is necessary with solo mining as sMax is shown when starting the worker.
Issue 2: Requiring miners to use complex mathematical formula's is a significant issue to adoption.  I'm one of the best infrastructure managers out there, but it's been a long time since I was in math class. Further I would wager that no one outside the team has actually used the formulas.  I'd also wager most on the team do not actually calculate using this formula either.  Further, I am skeptical I could actually use the formula, there's many unclear and unstated aspects of Phala and those continue with the formula itself.  For example R^e > 1 _"is a Stake Multiplier set by the network (Khala or Phala)."_. It's not stated how to obtain this value, it says its set by the network but then how does one obtain it to manually work through the math formula.  "C is the estimated cost of the miner rigs, inferred from the Performance Test."  The performance test no longer functions... this is just the first two lines of the formula and I'm at 100% stuck already.

If its expected that I use this math formula, please let me know as I will plan to give up on and stop mining for this project.  I don't want to work on something where there is such little bridge between the creators and folks such as myself looking to run infrastructure or unnecessary mathematical or technical barriers to 'prove one is worthy'.  which I don't think is actually possible due to variables in it that are undeterminable without being one of the people who wrote the formula and understands it at that level.  If the intention is to not have PRB miners except for an inner circle, being frank about that would save people time and frustration.  If Phala only wants people who can work through its formulas to mine, formulas which can't be worked by anyone outside the team, it seems like they'll be a very limited amount of folks who do.  I hope this feedback is helpful.

Happy to send a significant amount of PHA to someone that demonstrates that sMAX can actually be determined using the tokenomic formulas and makes a video.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/2354113/156623324-96b5e63e-9bda-4e50-8a44-eaf56a0c28bd.png">

**Comment by infrachris** [comment]
Thinking about it, maybe there's a step I'm missing in between starting PRB containers and adding a worker in PRB...  The PRB instructions stop at the docker commands, there's nothing after that in the wiki, so whatever has to happen between starting the PRB containers and having workers online is a mystery, I'm basically just guessing here.  Why not include the portion of steps required to add workers to PRB and have a running cluster.  I've written new documentation I'm happy to share with the community and can include the entire process end to end once I get past this last sticking point.

**Comment by DoyleGxd** [comment]
According to the formula of Phala Tokenomics in this page: https://wiki.phala.network/en-us/learn/tokenomics/tokenomics/#initial-v
V = {1+[ConfidenceScore · (Re - 1) ] } × (S+C)
Re(Khala) =1.5, C = 0.3×P/0.667, Vmax = 30000
So here it comes :
**Smax = 30000/(1+0.5×ConfidenceScore) - 0.3×P/0.667**
ConfidenceScore and P value are determined by your PC.

**Comment by DoyleGxd** [comment]
https://github.com/Phala-Network/solo-mining-scripts#manual-installation
According to this page, Command like 'sudo phala status' used to find out the P value(miner score).
![image](https://user-images.githubusercontent.com/98092850/156735790-c6f10f69-e869-45b4-930a-6ba2e6422046.png)
And ConfidenceScore can be searched like this.
https://wiki.phala.network/en-us/maintain/khala-mining/1-2-confidential-level-evaluation/
Most of the equipments seem to be level 5 (ConfidenceScore = 0.7)

**Comment by DoyleGxd** [comment]
I used to be a solo miner, maybe others can answer how to set up the prb
