### ISSUE TITLE
Feature Request: Show Smax in prb-monitor

### ISSUE THREAD

**Issue by Nexus2k** [Phala-Network/runtime-bridge#85]
I'd like to see Smax in the prb-monitor, the other values V and Ve are not that relevant.

**Comment by krhougs** [comment]
I'm afraid this feature can't be implemented for these reasons:
- `Smax` is calculated from V and Ve which are only accessible, hence the value is unable to be computed until the worker is registered on the chain;
- cycles should not be wasted by unrelated codes due to every Node.js process can only have a single thread.
